name: coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile code
      run: mvn clean compile       
  coverage:
     runs-on: ubuntu-latest
     name: maven coverage
     needs: compile
     steps:
       - name: coverage with maven
         uses: actions/checkout@v2
         with:
           java-version: 11
       - name: build and coverage
         run: mvn clean -B verify --no-transfer-progress
       - name: upload artifact
         uses: actions/upload-artifact@v2
         with: 
           name: index.html
           path: target/jacoco-site/index.html
           
       - name : get artifact content
         uses: actions/download-artifact@v2
         with:
           name: index.html
           path: target/jacoco-site
           
       - name: setup python
         uses: actions/setup-python@v2
         with: 
           python-version: '3.7.7'
           
       - name: install packages
         run: |
           python -m pip3 install --upgrade pip
           pip3 install pandas
           pip3 install tabulate
           pip3 install lxml
           
       - name: execute script
         run : python parser.py target/jacoco-site/index.html
         
         
         
       
#        - name: get file content
#          id : content
#          run: echo ::set-output name=content::$(cat /home/runner/work/PlayWithVertx/PlayWithVertx/target/jacoco-site/index.html)
#        - name: test output
#          run: echo ${{steps.content.output.content}}
         
#        - uses: kailash/mvn-coverage@v0.0.1
#          with:
#            file_path: /home/runner/work/PlayWithVertx/PlayWithVertx/target/jacoco-site/index.html
     
  
